const express = require("express");
const router = express.Router();
const Users = require("../controllers/usersController");
router.post("/doSignUp", Users.doSignUp);
router.post("/doSignIn", Users.doSignIn);
router.post('/authentication', Users.authentication);
router.get('/logout', Users.logout);
router.post('/activate', Users.activate);
router.post('/forgotPassword', Users.forgotPassword);
module.exports = router;